ait_mapping = {
    "AMiner: New characters in DNS domain.": MicroAttackStage.HOST_DISC,
    "AMiner: CPU value out of expected range in monitoring logs.": MicroAttackStage.BRUTE_FORCE_CREDS,
    "AMiner: New ip address in DNS logs.": MicroAttackStage.NON_MALICIOUS,
    "AMiner: Unusual occurrence frequencies of Apache Access logs.": MicroAttackStage.INFO_DISC,
    "AMiner: New cred_disp parameter combination in Audit logs.": MicroAttackStage.PRIV_ESC,
    "AMiner: New user_cmd parameter combination in Audit logs.": MicroAttackStage.PRIV_ESC,
    "AMiner: New user_end parameter combination in Audit logs.": MicroAttackStage.PRIV_ESC,
    "SURICATA HTTP invalid response chunk len": MicroAttackStage.SERVICE_DISC,
    "AMiner: Unusual occurrence frequencies of query records in DNS logs.": MicroAttackStage.NON_MALICIOUS,
    "AMiner: New user_auth parameter combination in Audit logs.": MicroAttackStage.PRIV_ESC,
    "AMiner: New service_start parameter combination in Audit logs.": MicroAttackStage.PRIV_ESC,
    "CMS (WordPress or Joomla) brute force attempt.": MicroAttackStage.BRUTE_FORCE_CREDS,
    "SURICATA TLS invalid record type": MicroAttackStage.USER_PRIV_ESC,
    "CMS (WordPress or Joomla) login attempt.": MicroAttackStage.SERVICE_DISC,
    "ET INFO Observed DNS Query to .cloud TLD": MicroAttackStage.NON_MALICIOUS,
    "ET POLICY GNU/Linux APT User-Agent Outbound likely related to package management": MicroAttackStage.NON_MALICIOUS,
    "AMiner: High entropy in Apache Access request.": MicroAttackStage.PUBLIC_APP_EXP,
    "SURICATA HTTP unable to match response to request": MicroAttackStage.NON_MALICIOUS,
    "PAM: User login failed.": MicroAttackStage.NON_MALICIOUS,
    "Dovecot Invalid User Login Attempt.": MicroAttackStage.NON_MALICIOUS,
    "AMiner: CPU value deviates from average in monitoring logs.": MicroAttackStage.BRUTE_FORCE_CREDS,
    "AMiner: Unusual occurrence frequencies of DNS query IPs.": MicroAttackStage.NON_MALICIOUS,
    "PAM: Login session closed.": MicroAttackStage.USER_PRIV_ESC,
    "Successful sudo to ROOT executed.": MicroAttackStage.PRIV_ESC,
    "AMiner: New user_start parameter combination in Audit logs.": MicroAttackStage.PRIV_ESC,
    "AMiner: New cred_acq parameter combination in Audit logs.": MicroAttackStage.PRIV_ESC,
    "AMiner: New user_acct parameter combination in Audit logs.": MicroAttackStage.PRIV_ESC,
    "AMiner: New service_stop parameter combination in Audit logs.": MicroAttackStage.PRIV_ESC,
    "SURICATA SMTP no server welcome message": MicroAttackStage.SERVICE_DISC,
    "Suspicious URL access.": MicroAttackStage.SERVICE_DISC,
    "AMiner: New event type.": MicroAttackStage.SERVICE_SPECIFIC,
    "AMiner: New request method in Apache Access log.": MicroAttackStage.SERVICE_DISC,
    "Apache: Attempt to access forbidden file or directory.": MicroAttackStage.SERVICE_DISC,
    "Apache: Attempt to access forbidden directory index.": MicroAttackStage.SERVICE_DISC,
    "Web server 400 error code.": MicroAttackStage.SERVICE_DISC,
    "SURICATA TLS invalid SSLv2 header": MicroAttackStage.SERVICE_DISC,
    "SURICATA SMTP invalid reply": MicroAttackStage.SERVICE_DISC,
    "AMiner: New status code in Apache Access log.": MicroAttackStage.SERVICE_DISC,
    "AMiner: New characters in Apache Access request.": MicroAttackStage.SERVICE_DISC,
    "Multiple web server 400 error codes from same source ip.": MicroAttackStage.SERVICE_DISC,
    "AMiner: Unusual occurrence frequencies of Apache Access request methods.": MicroAttackStage.SERVICE_DISC,
    "Common web attack.": MicroAttackStage.SERVICE_DISC,
    "PAM: Login session opened.": MicroAttackStage.USER_PRIV_ESC,
    "User successfully changed UID.": MicroAttackStage.PRIV_ESC,
    "AMiner: New login parameter combination in Audit logs.": MicroAttackStage.PRIV_ESC,
    "First time user executed sudo.": MicroAttackStage.PRIV_ESC,
    "AMiner: New cred_refr parameter combination in Audit logs.": MicroAttackStage.PRIV_ESC,
    "sshd: insecure connection attempt (scan).": MicroAttackStage.SERVICE_DISC,
    "Web server 500 error code (Internal Error).": MicroAttackStage.SERVICE_DISC,
    "syslog: User authentication failure.": MicroAttackStage.NON_MALICIOUS,
    "SURICATA TLS certificate invalid der": MicroAttackStage.NON_MALICIOUS,
    "AMiner: New user_login parameter combination in Audit logs.": MicroAttackStage.PRIV_ESC,
    "sshd: authentication success.": MicroAttackStage.PRIV_ESC,
    "AMiner: Unusual occurrence frequencies of DNS log events.": MicroAttackStage.PRIV_ESC,
    "AMiner: High entropy in DNS domain.": MicroAttackStage.NON_MALICIOUS,
    "ET DNS DNS Lookup for localhost.DOMAIN.TLD": MicroAttackStage.NON_MALICIOUS,
    "AMiner: Unusual occurrence frequencies of DNS query records.": MicroAttackStage.DATA_EXFILTRATION,
    "AMiner: New syscall parameter combination in Audit logs.": MicroAttackStage.PRIV_ESC,
    "ET INFO Session Traversal Utilities for NAT (STUN Binding Request)": MicroAttackStage.NON_MALICIOUS,
    "First time this IDS alert is generated.": MicroAttackStage.NON_MALICIOUS,
}
